In [8]:
import numpy as np

def positional_encoding(seq_length: int, d_model: int) -> np.ndarray:
    """
    Generate sinusoidal positional encodings.
    """
    # Position indices: [0, 1, 2, ..., max_seq_len-1] → shape (max_seq_len, 1)
    positions = np.arange(seq_length)[:, np.newaxis]

    # Dimension indices: [0, 2, 4, ..., d_model-2] → shape (1, d_model//2)
    dims = np.arange(0, d_model, 2)[np.newaxis, :]

    # Compute all angles at once
    angles = positions / (10000 ** (dims / d_model))

    # Allocate output
    PE = np.zeros((seq_length, d_model))

    # Fill even columns with sin, odd columns with cos
    PE[:, 0::2] = np.sin(angles)  # 0, 2, 4, ...
    PE[:, 1::2] = np.cos(angles)  # 1, 3, 5, ...

    return PE

print(positional_encoding(seq_length = 4, d_model = 6))

[[ 0.          1.          0.          1.          0.          1.        ]
 [ 0.84147098  0.54030231  0.04639922  0.99892298  0.00215443  0.99999768]
 [ 0.90929743 -0.41614684  0.0926985   0.99569422  0.00430886  0.99999072]
 [ 0.14112001 -0.9899925   0.1387981   0.9903207   0.00646326  0.99997911]]


In [ ]:
import numpy as np

positions = np.arange(50)[:, np.newaxis]
dims = np.arange(0, 64, 2)[np.newaxis, :]
angles = positions / 10000 ** dims/

dims

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
        32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62]])